import { NextRequest, NextResponse } from "next/server"
import { randomBytes } from "crypto"
import QRCode from "qrcode"
import { createClient } from "@/lib/supabase/server"
import { requireAdminApi } from "@/lib/auth/guards"

export async function POST(req: NextRequest) {
  try {
    const admin = await requireAdminApi()
    if (admin.error) return admin.error

    const body = await req.json()
    if (!body || typeof body !== "object" || Array.isArray(body)) {
      return NextResponse.json({ error: "A valid action payload is required." }, { status: 400 })
    }

    const { action, payload } = body
    if (typeof action !== "string" || !action.trim()) {
      return NextResponse.json({ error: "Action is required" }, { status: 400 })
    }
    if (!payload || typeof payload !== "object" || Array.isArray(payload)) {
      return NextResponse.json({ error: "A valid action payload is required." }, { status: 400 })
    }

    const supabase = createClient()

    switch (action) {
      case "update_consultation_status": {
        const { id, status, admin_notes } = payload
        const updateData: Record<string, unknown> = { status, updated_at: new Date().toISOString() }
        if (admin_notes !== undefined) updateData.admin_notes = admin_notes

        const { error } = await (supabase.from("consultation_requests") as any)
          .update(updateData)
          .eq("id", id)

        if (error) {
          return NextResponse.json({ error: error.message }, { status: 400 })
        }
        return NextResponse.json({ success: true, message: "Consultation status updated" })
      }

      case "update_startup_status": {
        const { id, status } = payload
        const { error } = await (supabase.from("startup_applications") as any)
          .update({ status, updated_at: new Date().toISOString() })
          .eq("id", id)

        if (error) {
          return NextResponse.json({ error: error.message }, { status: 400 })
        }
        return NextResponse.json({ success: true, message: "Startup application status updated" })
      }

      case "toggle_course_publish": {
        const { id, is_published } = payload
        const { error } = await (supabase.from("courses") as any)
          .update({ is_published })
          .eq("id", id)

        if (error) {
          return NextResponse.json({ error: error.message }, { status: 400 })
        }
        return NextResponse.json({ success: true, message: "Course status updated" })
      }

      case "toggle_course_popular": {
        const { id, is_popular } = payload
        const { error } = await (supabase.from("courses") as any)
          .update({ is_popular })
          .eq("id", id)

        if (error) {
          return NextResponse.json({ error: error.message }, { status: 400 })
        }
        return NextResponse.json({ success: true, message: "Course popularity updated" })
      }

      case "issue_certificate": {
        const {
          recipient_name,
          course_title,
          course_id,
          user_id,
          verification_code,
          grade,
          issue_date,
        } = payload

        if (verification_code !== undefined) {
          return NextResponse.json(
            { error: "Verification codes are generated by the server." },
            { status: 400 }
          )
        }

        if (
          typeof recipient_name !== "string" ||
          !recipient_name.trim() ||
          recipient_name.trim().length > 200 ||
          typeof course_title !== "string" ||
          !course_title.trim() ||
          course_title.trim().length > 200
        ) {
          return NextResponse.json(
            { error: "Recipient name and course title are required." },
            { status: 400 }
          )
        }

        const siteUrl = process.env.NEXT_PUBLIC_SITE_URL
        if (!siteUrl) {
          return NextResponse.json(
            { error: "Set NEXT_PUBLIC_SITE_URL before issuing certificates." },
            { status: 503 }
          )
        }

        let baseUrl: URL
        try {
          baseUrl = new URL(siteUrl)
        } catch {
          return NextResponse.json(
            { error: "NEXT_PUBLIC_SITE_URL must be a valid absolute URL." },
            { status: 500 }
          )
        }
        if (
          !["http:", "https:"].includes(baseUrl.protocol) ||
          (process.env.NODE_ENV === "production" && baseUrl.protocol !== "https:")
        ) {
          return NextResponse.json(
            { error: "NEXT_PUBLIC_SITE_URL must use HTTPS in production." },
            { status: 500 }
          )
        }

        let issueDate = new Date().toISOString().slice(0, 10)
        if (issue_date !== undefined) {
          if (typeof issue_date !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(issue_date)) {
            return NextResponse.json({ error: "Issue date must use YYYY-MM-DD format." }, { status: 400 })
          }
          const parsedIssueDate = new Date(`${issue_date}T00:00:00.000Z`)
          if (
            Number.isNaN(parsedIssueDate.getTime()) ||
            parsedIssueDate.toISOString().slice(0, 10) !== issue_date
          ) {
            return NextResponse.json({ error: "Issue date is not a valid calendar date." }, { status: 400 })
          }
          issueDate = issue_date
        }

        const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
        for (const [field, value] of [["course_id", course_id], ["user_id", user_id]] as const) {
          if (value !== undefined && value !== null && value !== "" &&
              (typeof value !== "string" || !uuidPattern.test(value))) {
            return NextResponse.json({ error: `${field} must be a valid UUID.` }, { status: 400 })
          }
        }

        const certificateInput = {
          recipient_name: recipient_name.trim(),
          course_title: course_title.trim(),
          course_id: typeof course_id === "string" && course_id ? course_id : null,
          user_id: typeof user_id === "string" && user_id ? user_id : null,
          grade: typeof grade === "string" && grade.trim() ? grade.trim().slice(0, 100) : "Distinction",
          issue_date: issueDate,
          is_valid: true,
        }

        let issuedCertificate: Record<string, unknown> | null = null
        let generatedCode = ""
        let verificationUrlString = ""
        let qrCode = ""
        let insertError: { code?: string; message: string } | null = null

        for (let attempt = 0; attempt < 3; attempt++) {
          generatedCode = `TG-${new Date().getFullYear()}-${randomBytes(12)
            .toString("hex")
            .toUpperCase()}`
          const verificationUrl = new URL("/verify", baseUrl)
          verificationUrl.searchParams.set("code", generatedCode)
          verificationUrlString = verificationUrl.toString()
          qrCode = await QRCode.toDataURL(verificationUrlString, {
            errorCorrectionLevel: "M",
            margin: 1,
            width: 320,
          })

          const { data, error } = await (supabase.from("certificates") as any)
            .insert({ ...certificateInput, verification_code: generatedCode })
            .select(
              "id, certificate_number, verification_code, recipient_name, course_title, issue_date, grade, is_valid, created_at"
            )
            .single()

          if (!error) {
            issuedCertificate = data
            insertError = null
            break
          }

          insertError = error
          if (error.code !== "23505") break
        }

        if (insertError || !issuedCertificate) {
          console.error("Certificate issuance failed:", insertError)
          return NextResponse.json(
            { error: "Certificate could not be issued. Please try again." },
            { status: 503 }
          )
        }

        return NextResponse.json({
          success: true,
          certificate: issuedCertificate,
          verification_url: verificationUrlString,
          qr_code: qrCode,
        })
      }

      case "toggle_certificate_validity": {
        const { id, is_valid } = payload
        const { error } = await (supabase.from("certificates") as any)
          .update({ is_valid })
          .eq("id", id)

        if (error) {
          return NextResponse.json({ error: error.message }, { status: 400 })
        }
        return NextResponse.json({ success: true, message: "Certificate validity toggled" })
      }

      case "update_message_status": {
        const { id, status } = payload
        const { error } = await (supabase.from("contact_messages") as any)
          .update({ status })
          .eq("id", id)

        if (error) {
          return NextResponse.json({ error: error.message }, { status: 400 })
        }
        return NextResponse.json({ success: true, message: "Message status updated" })
      }

      default:
        return NextResponse.json({ error: `Unknown action: ${action}` }, { status: 400 })
    }
  } catch (error: any) {
    console.error("Admin action API error:", error)
    return NextResponse.json({ error: error.message || "Internal server error" }, { status: 500 })
  }
}
